<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta content="IE=edge" http-equiv="X-UA-Compatible">
	<meta content="width=device-width, initial-scale=1" name="viewport">
	<title>Информационно-образовательная среда СГТУ | ИОС</title>
	<link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="css/custom.css" rel="stylesheet"><!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
	<link href="images2/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180">
	<link href="images2/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png">
	<link href="images2/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png">
	<link href="/site.webmanifest" rel="manifest">
	<link href="images2/safari-pinned-tab.svg" rel="mask-icon">
	<meta content="#da532c" name="msapplication-TileColor">
	<meta content="#ffffff" name="theme-color">
</head>
<body>
	<!-- Navigation -->
	<nav class="navbar navbar-default navbar-fixed-top" id="siteNav" role="navigation">
		<div class="container">
			<!-- Logo and responsive toggle -->
			<div class="navbar-header">
				<button class="navbar-toggle" data-target="#navbar" data-toggle="collapse" type="button"><span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button> <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-book"></span> ИОС СГТУ</a>
			</div><!-- Navbar links -->
			<div class="collapse navbar-collapse" id="navbar">
				<ul class="nav navbar-nav navbar-right">
					<li class="active">
						<a href="#">Домой</a>
					</li>
					<li>
						<a href="#">Переход1</a>
					</li>
					<li class="dropdown">
						<a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">Список1<span class="caret"></span></a>
						<ul aria-labelledby="about-us" class="dropdown-menu">
							<li>
								<a href="#">ЭлементСписка1</a>
							</li>
							<li>
								<a href="#">ЭлементСписка2</a>
							</li>
							<li>
								<a href="#">ЭлементСписка3</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Переход2</a>
					</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container -->
	</nav><!-- Header -->
	<header>
		<div class="header-content">
			<div class="header-content-inner">
				<h2>Информационно-образовательная среда</h2>
				<p>Добро пожаловать в ИОС СГТУ</p><a class="btn btn-primary btn-lg" href="#">Войти в систему</a>
			</div>
		</div>
	</header><!-- Intro Section -->
	<section class="intro">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<span class="glyphicon glyphicon-education" style="font-size: 60px"></span>
					<h2 class="section-heading">Информационно образовательная среда СГТУ</h2>
					<p class="text-light">предоставляет собой единый интерфейс общего доступа к данным, получаемым из разных источников и образовательных приложений</p>
				</div>
			</div>
		</div>
	</section><!-- Content 1 -->
	<section class="content">
		<div class="container">
			<div class="row">
				<div class="col-sm-6"><img alt="" class="img-responsive img-circle center-block" src="images/sstu.jpg"></div>
				<div class="col-sm-6">
					<h2 class="section-header">Ваше будущее начинается здесь!</h2>
					<p class="lead text-muted">В СГТУ обучается <span class="counter" style="font-weight: bold;">26466</span> студентов. В 2005 году только на первый курс зачислено <span class="counter" style="font-weight: bold;">1478</span> студентов. В настоящее время в вузе работает <span class="counter" style="font-weight: bold;">1175</span> преподавателей, в том числе <span class="counter" style="font-weight: bold;">200</span> профессоров и докторов наук, <span class="counter" style="font-weight: bold;">590</span> доцентов и кандидатов наук, свыше <span class="counter" style="font-weight: bold;">60</span> преподавателей являются действительными членами и членами-корреспондентами различных общественных академий РФ.</p><a class="btn btn-primary btn-lg" href="#">Хочу учиться</a>
				</div>
			</div>
		</div>
	</section><!-- Content 2 -->
	<section class="content content-2">
		<div class="container">
			<div class="row">
				<div class="col-sm-6">
					<h2 class="section-header">Региональный опорный университет</h2>
					<p class="lead text-light">В 2014 году агентство <b>«Эксперт РА»</b>, включило вуз в список высших учебных заведений <b>Содружества Независимых Государств</b>, где ему был присвоен рейтинговый класс «Е» (достаточный уровень подготовки выпускников).</p><a class="btn btn-default btn-lg" href="#">Убедиться в этом</a>
				</div>
				<div class="col-sm-6"><img alt="" class="img-responsive img-circle center-block" src="images/teachers.jpg"></div>
			</div>
		</div>
	</section><!-- Promos -->
	<div class="container-fluid">
		<div class="row promo">
			<a href="#">
			<div class="col-md-4 promo-item item-1">
				<h3>Переход1</h3>
			</div></a> <a href="#">
			<div class="col-md-4 promo-item item-2">
				<h3>Переход2</h3>
			</div></a> <a href="#">
			<div class="col-md-4 promo-item item-3">
				<h3>Переход3</h3>
			</div></a>
		</div>
	</div><!-- /.container-fluid -->
	<!-- Content 3 -->
	<section class="content content-3">
		<div class="container">
			<h2 class="section-header"><span class="glyphicon glyphicon-pencil text-primary"></span><br>
			Наша система - это</h2>
			<p class="lead text-muted">Доступ ко всем службам из любой точки Интернета с помощью веб-интерфейса и единой точки входа</p><!-- <span class="glyphicon glyphicon-paperclip">&nbsp;</span><span class="glyphicon glyphicon-blackboard">&nbsp;</span>&nbsp;<span class="glyphicon glyphicon-globe"></span> -->
			<p class="lead text-muted">Удобные средства повышения эффективности работы учащихся и преподавателей</p>
			<p class="lead text-muted">Упрощение выполнения стандартных задач и уменьшение растущей нагрузки на преподавателей, администраторов и специалистов по ИКТ</p>
			<p class="lead text-muted">И многое другое...</p><a class="btn btn-primary btn-lg" href="#">Подробнее</a>
		</div>
	</section><!-- Footer -->
	<footer class="page-footer">
		<!-- Contact Us -->
		<div class="contact">
			<div class="container">
				<h2 class="section-heading">Наши контакты</h2>
				<p><span class="glyphicon glyphicon-earphone"></span><br>
				+7(800)555-35-35</p>
				<p><span class="glyphicon glyphicon-envelope"></span><br>
				info@example.com</p>
			</div>
		</div><!-- Copyright etc -->
		<div class="small-print">
			<div class="container">
				<p>Copyright &copy; Mikhalyov Group, IVCHT-21, SSTU 2020</p>
			</div>
		</div>
	</footer><!-- jQuery -->
	<script src="js/jquery-1.11.3.min.js">
	</script> <!-- Bootstrap Core JavaScript -->
	 
	<script src="js/bootstrap.min.js">
	</script> <!-- Plugin JavaScript -->
	 
	<script src="js/jquery.easing.min.js">
	</script> <!-- Custom Javascript -->
	 
	<script src="js/custom.js">
	</script> <!-- <script src="js/jquery.counterup.min.js"></script>
    <script src="js/lib/jquery.waypoints.min.js"></script> -->
	 
	<script>
	       jQuery(document).ready(function(){
	           $('.counter').counterUp({
	           delay: 10,
	           time: 1000
	           });
	       });
	</script>
</body>
</html>